---
title: Will the real data please stand up?
output: pdf_document
---

```{r include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE
  , warning = FALSE
  , message = FALSE
  , fig.height = 4
  , cache = TRUE
)

library(tidyverse)
library(gridExtra)
```

In each exhibit below, there is a display of "real" sample data, which follows a specific probability distribution. There are also 19 simulated samples which have the same mean and standard deviation, but follow a _different_ probability distribution. The real data is different in each plot. Make your guesses now and we will reveal the answers during the presentation.

```{r include = FALSE}
set.seed(1234)
meanlog_actual <- log(10e3)
sdlog_actual <- 0.5

tbl_obs <- tibble(
  x = rlnorm(5e3, meanlog = meanlog_actual, sdlog = sdlog_actual)
)

tbl_obs$x %>% 
  summary()

```

```{r include= FALSE}
mean_sample <- tbl_obs$x %>% mean()
sd_sample <- tbl_obs$x %>% sd()
```

```{r include = FALSE}
library(MASS)
fit_lnorm <- fitdistr(
    tbl_obs$x
  , 'log-normal'
)

est_meanlog <- fit_lnorm$estimate[1]
est_sd <- fit_lnorm$estimate[2]

tbl_obs <- tbl_obs %>% 
  mutate(
      percentile = percent_rank(x)
    , density_lnorm = dlnorm(x, est_meanlog, est_sd)
  )
```

```{r include = FALSE}
shape <- (mean_sample / sd_sample) ^ 2
rate <- mean_sample / sd_sample ^ 2

library(MASS)
fit_weibull <- fitdistr(tbl_obs$x, 'weibull')
fit_gamma <- fitdistr(tbl_obs$x, 'gamma', lower = .01)

tbl_obs <- tbl_obs %>% 
  mutate(
      density_gamma_fitdistr = dgamma(x, fit_gamma$estimate[1], fit_gamma$estimate[2])
    , density_gamma_mom = dgamma(x, shape, rate)
    , density_weibull = dweibull(x, fit_weibull$estimate[1], fit_weibull$estimate[2])
  )

```


```{r}
library(nullabor)
library(ggridges)

null_dist('x', 'gamma', params = list(shape = shape, rate = rate)) %>% 
  lineup(tbl_obs, pos = 13) %>% 
  mutate(sample = as.factor(.sample)) %>% 
  ggplot(aes(x, y = sample)) + 
  geom_density_ridges()
```

```{r fig.height=3.5}
null_dist('x', 'gamma', params = list(shape = shape, rate = rate)) %>% 
  lineup(tbl_obs, pos = 7) %>% 
  mutate(sample = as.factor(.sample)) %>%
  ggplot(aes(x)) + 
  geom_histogram() + 
  facet_wrap(~ sample) + 
  theme(axis.text.x = element_blank())
```

```{r }
null_dist('x', 'gamma', params = list(shape = shape, rate = rate)) %>% 
  lineup(tbl_obs, pos = 17) %>% 
  mutate(sample = as.factor(.sample)) %>%
  ggplot(aes(sample, x)) + 
  geom_boxplot()
```

```{r}
tbl_lineup_2 <- null_dist('x', 'weibull', params = list(shape = fit_weibull$estimate[1], scale = fit_weibull$estimate[2])) %>% 
  lineup(tbl_obs, pos = 5) %>% 
  mutate(sample = as.factor(.sample))

tbl_lineup_2 %>% 
  ggplot(aes(sample, x)) + 
  geom_boxplot()
```
